swagger: "2.0"
info:
    title: Argent Bank API Transactions Documentation
    description: Provides an API template for user account transactions
    version: 2.0.0
    termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v2
schemes:
    - http
paths:
    /user/transactions/month:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction Module
            summary: All transactions for the current month
            description: API for fetching current month transactions
            produces:
                - application/json
            responses:
                "200":
                    description: User transactions retrieved successfully
                    schema:
                        $ref: "#/definitions/allTransactionsResponse"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transactions not found
                "500":
                    description: Internal Server Error
  
    /user/transaction/details/{id}:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction Module
            summary: Transaction details
            description: API for fetching a transaction details
    
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction retrieved successfully
                    schema:
                        $ref: "#/definitions/ApiTransactionResponse"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transaction not found
                "500":
                    description: Internal Server Error
        put:
            security:
                - Bearer: []
            tags:
                - Transaction Module
            summary: Transaction changes API
            description: API for updating a transaction
            parameters:
                - in: header
                  name: Authorization
                  description: Attach Bearer JWT token
                  required: true
                  type: string
                - in: path
                  name: id
                  description: Id of the transaction that needs to be edited
                  required: true
                  type: string
                - in: body
                  name: body
                  description: Update transaction
                  required: true
                  schema:
                      $ref: "#/definitions/updateTransaction"
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction edited successfully
                    schema:
                        $ref: "#/definitions/ApiTransactionResponse"
                "400":
                    description: Invalid Fields
                "401":
                    description: Unauthorized
                "404":
                    description: Transaction not found
                "500":
                    description: Internal Server Error
     
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
definitions:
    allTransactionsResponse:
       type: object
       properties:
          status:
            type: integer
          message:
            type: string
          month:
            type: string
          transactions:
                type: object
                properties:
                    id:
                        type: string
                        description: Id of the first transaction
                    date:
                        type: string
                        description: Date of the transaction
                    description:
                        type: string
                        description: Description transaction
                    amount:
                        type: number
                        description: Amount 
                    balance:
                        type: number
                        description: Balance
    updateTransaction:
       type: object
       properties:
            category:
                type: string
                description: New category of this transaction
            note:
                type: string
                description: New notes of this transaction
    ApiTransactionResponse:
        properties:
            status:
              type: integer
            message:
              type: string
            body:
              type: object
              properties:
                id:
                  type: integer
                transaction type:
                  type: string
                  description: Type of transaction