swagger: '2.0'
info:
  title: Bank Argent API Transactions and User documentation
  description: Contains all available API endpoints in this codebase and provides an API template for user account transactions
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: All transactions for the current month
      description: API for fetching current month transactions
      produces:
        - application/json
      responses:
        "200":
          description: User transactions retrieved successfully
          schema:
            $ref: "#/definitions/AllTransactionsResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /transactions/{TransactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction details
      description: API for fetching a transaction details
      parameters:
        - in: path
          name: TransactionId
          description: Id of the transaction that needs to be edited
          required: true
          type: string
      produces:
          - application/json
      responses:
        "200":
          description: Transaction retrieved successfully
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction changes API
      description: API for updating a transaction
      parameters:
        - in: path
          name: TransactionId
          description: Id of the transaction
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction
          required: true
          schema:
           $ref: "#/definitions/UpdateTransactionResponse"
      produces:
        - application/json
      responses:
          "200":
            description: Transaction edited successfully
            schema:
              $ref: "#/definitions/TransactionResponse"
          "400":
            description: Invalid Fields
          "401":
            description: Unauthorized
          "404":
            description: Transaction not found
          "500":
            description: Internal Server Error
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  AllTransactionsResponse:
    type: object
    properties:
      status:
        type: integer
        example: "200"
      message:
        type: string
      month:
        type: string
      accounts:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              description: Id of the account
            name:
              type: string
              description: Name of account
            transactions:
              type: array
              items:
                type: object
                properties:
                  id:
                   type: string
                   description: Id of the first transaction
                  date:
                   type: string
                   format: date
                   description: Date of the transaction
                  description:
                   type: string
                   description: Description transaction
                  amount:
                   type: number
                   description: Amount
                  balance:
                   type: number
                   description: Balance
                  type:
                   type: string
                   description: Type of transaction
                  category:
                    type: string
                    description: Category of transaction
                  note:
                    type: string
                    description: comments
    example:
      status: 200
      message: "Transactions retrieved successfully"
      body:
        month: "February"
        account:
          - id: "1ef3"
            name: "Checking"
            transactions:
              - id: "1"
                date: "27/02/2020"
                description: "Golden Sun Bakery"
                amount: "$8.00"
                balance: "$298.00"
                type: "Electronic"
                category: "Food"
                note: "Lorem ipsum"
              - id: "2"
                date: "27/02/2020"
                description: "Golden Sun Bakery"
                amount: "$8.00"
                balance: "$298.00"
                type: "Electronic"
                category: "Hobbies"
                note: "Lorem"
  TransactionResponse:
     type: object
     properties:
      status:
        type: integer
        example: "200"
      message:
        type: string
        example: "Success"
      body:
        type: object
        properties:
          id:
            type: string
            description: Id of the first transaction
          date:
            type: string
            format: date
            description: Date of the transaction
          description:
            type: string
            description: Description transaction
          amount:
            type: number
            description: Amount
          balance:
            type: number
            description: Balance
          type:
            type: string
            description: Type of transaction
          category:
            type: string
            description: Category of transaction
          note:
            type: string
            description: comments
  UpdateTransactionResponse:
    type: object
    properties:
      category:
        type: string
        description: New category of this transaction
      note:
        type: string
        description: New notes of this transaction
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
